routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Admin\DepartmentController;

use App\Http\Controllers\Admin\RoleController;

use App\Http\Controllers\Admin\UserController;

use App\Http\Controllers\Admin\PermissionController;

use App\Http\Controllers\Admin\LoanTypeController;

use App\Http\Controllers\Admin\LoanController;

use App\Http\Controllers\Admin\NewsController;

use App\Http\Controllers\Admin\ReportController;

use App\Http\Controllers\Admin\JobTypeController;

use App\Http\Controllers\Admin\JobController;

use App\Http\Controllers\Admin\ProfileController;



use App\Http\Controllers\FrontEnd\AboutController;

use App\Http\Controllers\FrontEnd\ApplyLoanController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('/',[App\Http\Controllers\FrontEnd\FrontEndController::class, 'homepage']);

// =============== Product ===============
Route::get('product', [App\Http\Controllers\FrontEnd\ProductController::class, 'index'])->name('product');

Route::get('/product/{id}', [App\Http\Controllers\FrontEnd\ProductController::class, 'detail'])->name('details');


// =============== Apply Loan ===============

Route::get('applyotherloan', [App\Http\Controllers\Admin\ApplyLoanController::class, 'applyotherloan'])->name('applyotherloan');

Route::get('getState', [App\Http\Controllers\Admin\ApplyLoanController::class, 'getState'])->name('getState');

Route::get('getCity', [App\Http\Controllers\Admin\ApplyLoanController::class, 'getCity'])->name('getCity');



Route::post('applyotherloanid', [App\Http\Controllers\Admin\ApplyLoanController::class, 'storeapplyotherloan'])->name('applyotherloanid.storeapplyotherloan');

Route::get('applyloan/{id}', [App\Http\Controllers\Admin\ApplyLoanController::class, 'applyloan'])->name('applyloan');

Route::post('applyloanid/{id}', [App\Http\Controllers\Admin\ApplyLoanController::class, 'storeapplyloan'])->name('applyloanid.storeapplyloan');


// =============== Report ===============

Route::resource('eadmin/reports', ReportController::class);
Route::get('report', [App\Http\Controllers\FrontEnd\ReportController::class, 'report'])->name('report');

// =============== News ===============

Route::get('news', [App\Http\Controllers\FrontEnd\NewsController::class, 'news'])->name('news');

Route::get('/news/{id}', [App\Http\Controllers\FrontEnd\NewsController::class, 'detail'])->name('detail');

// =============== Job ===============

Route::get('applyjob/{id}', [App\Http\Controllers\FrontEnd\JobController::class, 'applyjob'])->name('applyjob');

Route::get('job', [App\Http\Controllers\FrontEnd\JobController::class, 'job'])->name('job');

Route::post('applyjobid/{id}', [App\Http\Controllers\Admin\JobController::class, 'storeapplyjob'])->name('applyjobid.storeapplyjob');

Route::get('/job/{id}', [App\Http\Controllers\FrontEnd\JobController::class, 'detailjob'])->name('detailjob');

Route::get('job-category/{title_en}', [App\Http\Controllers\FrontEnd\JobController::class, 'jobcategory'])->name('jobcategory');

// =============== Contact ===============

Route::get('contact', [App\Http\Controllers\FrontEnd\ContactController::class, 'index'])->name('contact');


// =============== Compliant ===============

Route::get('applycompliant', [App\Http\Controllers\FrontEnd\CompliantController::class, 'applycompliant'])->name('applycompliant');

Route::post('applycompliant', [App\Http\Controllers\FrontEnd\CompliantController::class, 'storecompliant'])->name('applycompliant.storecompliant');




// =============== About ===============

Route::get('/about/license', [App\Http\Controllers\FrontEnd\AboutController::class, 'license'])->name('license');


Route::get('/about/organizational', [App\Http\Controllers\FrontEnd\AboutController::class, 'organizational'])->name('organizational');

Route::get('/about/management', [App\Http\Controllers\FrontEnd\AboutController::class, 'management'])->name('management');

Route::get('/about/background', [App\Http\Controllers\FrontEnd\AboutController::class, 'background'])->name('background');

Route::get('/about', [App\Http\Controllers\FrontEnd\AboutController::class, 'index'])->name('about');

Route::resource('profile', ProfileController::class);


// ================= Route Back End ================= 
//======================================================

Route::group(['middleware' => ['auth','has.permission']], function() {

    
    // =============== Home ===============

    Route::get('/home', [\App\Http\Controllers\Admin\HomeController::class, 'index'])
        ->name('home');


   
    

    Route::resource('posts', \App\Http\Controllers\Admin\PostController::class)
        ->only('create', 'store');

    Route::resource('departments', DepartmentController::class);

    Route::resource('roles', RoleController::class);

    Route::resource('permissions', PermissionController::class);

    Route::resource('users', UserController::class);

    // =============== Loan Type ===============

    Route::resource('eadmin/loantypes', LoanTypeController::class);

    // =============== Loans =============== 
    
    Route::resource('eadmin/loans', LoanController::class);

    // =============== Apply Loans =============== 
    Route::get('eadmin/applyed-loan', [App\Http\Controllers\Admin\ApplyLoanController::class, 'applyedloan'])->name('applyed-loan');

    Route::get('eadmin/applyed-loan/{id}', [App\Http\Controllers\Admin\ApplyLoanController::class, 'viewapplyedloan'])->name('applyed-loan.viewapplyedloan');

    // =============== News ===============

    Route::resource('eadmin/news', NewsController::class);

    // =============== Report ===============

    Route::resource('eadmin/reports', ReportController::class);

    // =============== Jobs Type ===============

    Route::resource('eadmin/jobtypes', JobTypeController::class);

    // =============== Job ===============

    Route::resource('eadmin/job', JobController::class);

    Route::get('eadmin/applyed-job', [App\Http\Controllers\Admin\JobController::class, 'applyedjob'])->name('applyed-job');

    Route::get('eadmin/applyed-job/{id}', [App\Http\Controllers\Admin\JobController::class, 'viewapplyedjob'])->name('applyed-job.viewapplyedjob');

     // =============== Compliant ===============

     Route::get('eadmin/applyed-compliant', [App\Http\Controllers\FrontEnd\CompliantController::class, 'applyedcompliant'])->name('applyed-compliant');

     

     Route::get('eadmin/applyed-compliant/{id}', [App\Http\Controllers\FrontEnd\CompliantController::class, 'viewapplyedcompliant'])->name('applyed-compliant.viewapplyedcompliant');

     Route::patch('eadmin/aprove-compliant/{id}', [App\Http\Controllers\FrontEnd\CompliantController::class, 'aprove'])->name('aprove-compliant.aprove');

     Route::patch('eadmin/aprove-apply-job/{id}', [App\Http\Controllers\Admin\JobController::class, 'aprove'])->name('aprove-apply-job.aprove');
     Route::patch('eadmin/aprove-apply-loan/{id}', [App\Http\Controllers\Admin\ApplyLoanController::class, 'aprove'])->name('aprove-apply-loan.aprove');

});

require __DIR__.'/auth.php';

app/Models/Department.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Department extends Model
{
    use HasFactory;
    protected $guarded=[];
}

app/Http/Controllers/Admin/DepartmentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;

use Illuminate\Http\Request;

use App\Models\Department;

class DepartmentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $departments = Department::all();

        return view('admin.department.index',compact('departments'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
   
        return view('admin.department.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $this->validateForm($request);

        $data = $request->all();
        Department::create($data);
        return redirect()->back()->with('message','Department created Successfully!');
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        
        $department = Department::find($id);
        
        return view('admin.department.edit',compact('department'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $this->validateForm($request);
        $department = Department::find($id);
        $data = $request->all();
        $department->update($data);
        return redirect(route('departments.index'))->with('message','Department updated Successfully!');
       

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $department = Department::find($id);
        $department->delete();
        return redirect()->back()->with('message','Department Deleted Successfully!');
    }

    public function validateForm($request){
        return $this->validate($request,[
            'name'=>'required|string'
            

        ]);
    }
}

resources/views/admin/department/create.blade.php
@extends('admin.partails.master')

@section('content')


            @if (Session::has('message'))
            <div class="alert alert-success">
                {{Session::get('message')}}
            </div>
                
            @endif
            <nav class="page-breadcrumb">
					<ol class="breadcrumb">
						<li class="breadcrumb-item"><a href="{{route('departments.index')}}">{{__('globle.Action.Back')}}</a></li>
						<li class="breadcrumb-item active" aria-current="page">{{__('globle.Action.Create')}} {{__('sidebar.Department')}}</li>
					</ol>
			</nav>

				<div class="row">
					<div class="col-lg-6 grid-margin stretch-card">
						<div class="card">
							<div class="card-body">
								<h4 class="card-title">{{__('globle.Action.Create')}} {{__('sidebar.Department')}}</li>
                                </ol></h4>
								
								<form class="cmxform"  action="{{route('departments.store')}}" method="POST">@csrf
									<fieldset>
										<div class="form-group">
											<label for="name">{{__('globle.Name')}}</label>
											<input id="name" class="form-control @error('name') is-invalid @enderror"id="name" name="name" type="text">

                                            @error('name')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
										</div>
										<div class="form-group">
											<label for="description">{{__('globle.Description')}}</label>
											<textarea class="form-control" name="description" id="description" rows="10"></textarea>
										</div>
										
										
										<input class="btn btn-primary" type="submit" value="{{__('globle.Action.Create')}}">
									</fieldset>
								</form>
							</div>
						</div>
					</div>
					<div class="col-lg-6 grid-margin stretch-card">
						
					</div>
				</div>


@endsection

resources/views/admin/department/edit.blade.php
@extends('admin.partails.master')
@section('content')


        
        @if (Session::has('message'))
        <div class="alert alert-success">
            {{Session::get('message')}}
        </div>
            
        @endif
        <nav class="page-breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{route('departments.index')}}">{{__('globle.Action.Back')}}</a></li>
                    <li class="breadcrumb-item active" aria-current="page">{{__('globle.Action.Edit')}} {{__('sidebar.Department')}}</li>
                </ol>
        </nav>

            <div class="row">
                <div class="col-lg-6 grid-margin stretch-card">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">{{__('globle.Action.Create')}} {{__('sidebar.Department')}}</li>
                            </ol></h4>
                            
                            <form class="cmxform"  action="{{route('departments.update',[$department->id])}}" method="POST">@csrf
                                {{method_field('PATCH')}}
                                <fieldset>
                                    <div class="form-group">
                                        <label for="name">{{__('globle.Name')}}</label>
                                        <input id="name" class="form-control @error('name') is-invalid @enderror"id="name" name="name" type="text" value="{{$department->name}}">

                                        @error('name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                    </div>
                                    <div class="form-group">
                                        <label for="description">{{__('globle.Description')}}</label>
                                        <textarea class="form-control" name="description" id="description" rows="10">{{$department->description}}</textarea>
                                    </div>
                                    
                                    @if (@isset(auth()->user()->role->permission['name']['department']['can-edit']))
                                    <input class="btn btn-warning" type="submit" value="{{__('globle.Action.Update')}}">
                                    @endif
                                </fieldset>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 grid-margin stretch-card">
                    
                </div>
            </div>


@endsection

resources/views/admin/department/index.blade.php
@extends('admin.partails.master')

@section('content')

<div class="d-flex justify-content-between align-items-center flex-wrap grid-margin">
    <div>
      <h4 class="mb-3 mb-md-0">{{__('globle.Welcome_to')}} {{__('sidebar.Department')}}</h4>
    </div>
    <div class="d-flex align-items-center flex-wrap text-nowrap">
      <div class="input-group date datepicker dashboard-date mr-2 mb-2 mb-md-0 d-md-none d-xl-flex" id="dashboardDate">
        <span class="input-group-addon bg-transparent"><i data-feather="calendar" class=" text-primary"></i></span>
        <input type="text" class="form-control">
      </div>
      <button type="button" class="btn btn-outline-info btn-icon-text mr-2 d-none d-md-block">
        <i class="btn-icon-prepend" data-feather="download"></i>
        Import
      </button>
      <button type="button" class="btn btn-outline-primary btn-icon-text mr-2 mb-2 mb-md-0">
        <i class="btn-icon-prepend" data-feather="printer"></i>
        Print
      </button>
      {{-- <button type="button" class="btn btn-primary btn-icon-text mb-2 mb-md-0">
        <i class="btn-icon-prepend" data-feather="download-cloud"></i>
        Download Report
      </button> --}}
    </div>
  </div>

   
                <div class="mb-6">
                    <div class="row">
                        <div class="col-sm-12 col-md-6 d-flex mb-3">
                            
                            <div class="align-self-center">
                                @if (@isset(auth()->user()->role->permission['name']['department']['can-add'])) 
                                <a href="{{route('departments.create')}}">

                                    <button type="button" class="btn btn-primary btn-icon-text mb-2 mb-md-0">
                                        <i class="btn-icon-prepend" data-feather="plus-square"></i>
                                         {{__('sidebar.Department')}}
                                      </button>
                                   
                                </a>
                                @endif
                            </div>
                        </div>
                       
                            
                       
                       
                    </div>
                </div>

                @if (Session::has('message'))
                <div class="alert alert-success">
                    {{Session::get('message')}}
                </div>
                    
                @endif
            
                <div class="table-responsive">



                    


                    <div class="row">
                        <div class="col-md-12 grid-margin stretch-card">
                <div class="card">
                  <div class="card-body">
                    
                    
                    <div class="table-responsive">
                      <table id="dataTableExample" class="table">
                        <thead>
                          <tr>
                            <th class="py-6">{{__('globle.No')}}.</th>
                            <th class="py-6">{{__('globle.Name')}}</th>
                            {{-- <th class="py-6">{{__('globle.Description')}}</th> --}}
                            <th class="no-sort py-6">{{__('globle.Action.Action')}}</th>
                          </tr>
                        </thead>
                        <tbody>
                            @if (count($departments) > 0)
                            @foreach ($departments as $key => $department)
                          
                          <tr>
                            <td>{{ $key + 1 }}</td>
                            <td>{{$department->name}}</td>
                            {{-- <td>{{$department->description}}</td> --}}
                            <td>


                                @if (@isset(auth()->user()->role->permission['name']['department']['can-edit']))       
                                            <a href="{{route('departments.edit',[$department->id])}}">
                                                
                                                <i class="link-icon" data-feather="edit"></i>
                                            </a>

                                                 
                                @endif


                                @if (@isset(auth()->user()->role->permission['name']['department']['can-delete'])) 
                                                <!-- Button trigger modal -->
                                                <button type="button"  class="btn btn-link" data-toggle="modal" data-target="#exampleModal{{$department->id}}">
                                                    <i class="link-icon text-danger" data-feather="trash"></i>
                                                </button>
                                            @endif

                                                <!-- Modal -->
                                                <div class="modal fade" id="exampleModal{{$department->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                                    <div class="modal-dialog" role="document">
                                                        <form action="{{route('departments.destroy',[$department->id])}}" method="POST"> @csrf
                                                            {{method_field('DELETE')}}
                                                            <div class="modal-content">
                                                                <div class="modal-header">
                                                                <h5 class="modal-title" id="exampleModalLabel">Deleting Department</h5>
                                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                                    <span aria-hidden="true">&times;</span>
                                                                </button>
                                                                </div>
                                                                <div class="modal-body">
                                                                Do you want to delete
                                                                </div>
                                                                <div class="modal-footer">
                                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                                                <button type="submit" class="btn btn-danger">Delete</button>
                                                                </div>
                                                            </div>
                                                        </form>
                                                        
                                                    </div>
                                                </div>


                            </td>
                            
                          </tr>

                          @endforeach
                          @else

                                <div>No Table to Display</div>

                            @endif

                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
                        </div>
                    </div>


        

         

@endsection