routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Admin\DepartmentController;

use App\Http\Controllers\Admin\RoleController;

use App\Http\Controllers\Admin\UserController;

use App\Http\Controllers\Admin\PermissionController;

use App\Http\Controllers\Admin\LoanTypeController;

use App\Http\Controllers\Admin\LoanController;

use App\Http\Controllers\Admin\NewsController;

use App\Http\Controllers\Admin\ReportController;

use App\Http\Controllers\Admin\JobTypeController;

use App\Http\Controllers\Admin\JobController;

use App\Http\Controllers\Admin\ProfileController;



use App\Http\Controllers\FrontEnd\AboutController;

use App\Http\Controllers\FrontEnd\ApplyLoanController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('/',[App\Http\Controllers\FrontEnd\FrontEndController::class, 'homepage']);

// =============== Product ===============
Route::get('product', [App\Http\Controllers\FrontEnd\ProductController::class, 'index'])->name('product');

Route::get('/product/{id}', [App\Http\Controllers\FrontEnd\ProductController::class, 'detail'])->name('details');


// =============== Apply Loan ===============

Route::get('applyotherloan', [App\Http\Controllers\Admin\ApplyLoanController::class, 'applyotherloan'])->name('applyotherloan');

Route::get('getState', [App\Http\Controllers\Admin\ApplyLoanController::class, 'getState'])->name('getState');

Route::get('getCity', [App\Http\Controllers\Admin\ApplyLoanController::class, 'getCity'])->name('getCity');



Route::post('applyotherloanid', [App\Http\Controllers\Admin\ApplyLoanController::class, 'storeapplyotherloan'])->name('applyotherloanid.storeapplyotherloan');

Route::get('applyloan/{id}', [App\Http\Controllers\Admin\ApplyLoanController::class, 'applyloan'])->name('applyloan');

Route::post('applyloanid/{id}', [App\Http\Controllers\Admin\ApplyLoanController::class, 'storeapplyloan'])->name('applyloanid.storeapplyloan');


// =============== Report ===============

Route::resource('eadmin/reports', ReportController::class);
Route::get('report', [App\Http\Controllers\FrontEnd\ReportController::class, 'report'])->name('report');

// =============== News ===============

Route::get('news', [App\Http\Controllers\FrontEnd\NewsController::class, 'news'])->name('news');

Route::get('/news/{id}', [App\Http\Controllers\FrontEnd\NewsController::class, 'detail'])->name('detail');

// =============== Job ===============

Route::get('applyjob/{id}', [App\Http\Controllers\FrontEnd\JobController::class, 'applyjob'])->name('applyjob');

Route::get('job', [App\Http\Controllers\FrontEnd\JobController::class, 'job'])->name('job');

Route::post('applyjobid/{id}', [App\Http\Controllers\Admin\JobController::class, 'storeapplyjob'])->name('applyjobid.storeapplyjob');

Route::get('/job/{id}', [App\Http\Controllers\FrontEnd\JobController::class, 'detailjob'])->name('detailjob');

Route::get('job-category/{title_en}', [App\Http\Controllers\FrontEnd\JobController::class, 'jobcategory'])->name('jobcategory');

// =============== Contact ===============

Route::get('contact', [App\Http\Controllers\FrontEnd\ContactController::class, 'index'])->name('contact');


// =============== Compliant ===============

Route::get('applycompliant', [App\Http\Controllers\FrontEnd\CompliantController::class, 'applycompliant'])->name('applycompliant');

Route::post('applycompliant', [App\Http\Controllers\FrontEnd\CompliantController::class, 'storecompliant'])->name('applycompliant.storecompliant');




// =============== About ===============

Route::get('/about/license', [App\Http\Controllers\FrontEnd\AboutController::class, 'license'])->name('license');


Route::get('/about/organizational', [App\Http\Controllers\FrontEnd\AboutController::class, 'organizational'])->name('organizational');

Route::get('/about/management', [App\Http\Controllers\FrontEnd\AboutController::class, 'management'])->name('management');

Route::get('/about/background', [App\Http\Controllers\FrontEnd\AboutController::class, 'background'])->name('background');

Route::get('/about', [App\Http\Controllers\FrontEnd\AboutController::class, 'index'])->name('about');

Route::resource('profile', ProfileController::class);


// ================= Route Back End ================= 
//======================================================

Route::group(['middleware' => ['auth','has.permission']], function() {

    
    // =============== Home ===============

    Route::get('/home', [\App\Http\Controllers\Admin\HomeController::class, 'index'])
        ->name('home');


   
    

    Route::resource('posts', \App\Http\Controllers\Admin\PostController::class)
        ->only('create', 'store');

    Route::resource('departments', DepartmentController::class);

    Route::resource('roles', RoleController::class);

    Route::resource('permissions', PermissionController::class);

    Route::resource('users', UserController::class);

    // =============== Loan Type ===============

    Route::resource('eadmin/loantypes', LoanTypeController::class);

    // =============== Loans =============== 
    
    Route::resource('eadmin/loans', LoanController::class);

    // =============== Apply Loans =============== 
    Route::get('eadmin/applyed-loan', [App\Http\Controllers\Admin\ApplyLoanController::class, 'applyedloan'])->name('applyed-loan');

    Route::get('eadmin/applyed-loan/{id}', [App\Http\Controllers\Admin\ApplyLoanController::class, 'viewapplyedloan'])->name('applyed-loan.viewapplyedloan');

    // =============== News ===============

    Route::resource('eadmin/news', NewsController::class);

    // =============== Report ===============

    Route::resource('eadmin/reports', ReportController::class);

    // =============== Jobs Type ===============

    Route::resource('eadmin/jobtypes', JobTypeController::class);

    // =============== Job ===============

    Route::resource('eadmin/job', JobController::class);

    Route::get('eadmin/applyed-job', [App\Http\Controllers\Admin\JobController::class, 'applyedjob'])->name('applyed-job');

    Route::get('eadmin/applyed-job/{id}', [App\Http\Controllers\Admin\JobController::class, 'viewapplyedjob'])->name('applyed-job.viewapplyedjob');

     // =============== Compliant ===============

     Route::get('eadmin/applyed-compliant', [App\Http\Controllers\FrontEnd\CompliantController::class, 'applyedcompliant'])->name('applyed-compliant');

     

     Route::get('eadmin/applyed-compliant/{id}', [App\Http\Controllers\FrontEnd\CompliantController::class, 'viewapplyedcompliant'])->name('applyed-compliant.viewapplyedcompliant');

     Route::patch('eadmin/aprove-compliant/{id}', [App\Http\Controllers\FrontEnd\CompliantController::class, 'aprove'])->name('aprove-compliant.aprove');

     Route::patch('eadmin/aprove-apply-job/{id}', [App\Http\Controllers\Admin\JobController::class, 'aprove'])->name('aprove-apply-job.aprove');
     Route::patch('eadmin/aprove-apply-loan/{id}', [App\Http\Controllers\Admin\ApplyLoanController::class, 'aprove'])->name('aprove-apply-loan.aprove');

});

require __DIR__.'/auth.php';

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;


use App\Models\Department;

use App\Models\Role;



class User extends Authenticatable
{
    use  HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'address',
        'mobile_number',
        'department_id',
        'designation',
        'role_id',
        'image',
        'start_from'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

// =================Relation Ship ====================


    public function department (){
        return $this->hasOne(Department::class,'id', 'department_id');
    }

    
    public function role (){
        return $this->hasOne(Role::class, 'id', 'role_id');
    }


}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;

use Illuminate\Http\Request;

use App\Models\User;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    { 
        $users = User::all();
        return view('admin.user.index',compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'firstname'=>'required',
            'lastname'=>'required',
            'email'=>'required|string|email|max:255|unique:users',
            'password'=>'required|string',
            'department_id'=>'required',
            'role_id'=>'required',
            'image'=>'mimes:jpeg,jpg,png',
            'start_from'=>'required',
            'designation'=>'required'
        ]);

        $data = $request->all();
        if($request->hasFile('image')){
            $image = $request->image->hashName();
            $request->image->move(public_path('profile'),$image);
        }else{
            $image = 'avatar.png';
        }
        $data['name'] = $request->firstname.' '.$request->lastname;
        $data['image']=$image;
        $data['password']= bcrypt($request->password);
        User::create($data);
        
        return redirect()->back()->with('message','User created Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::find($id);
        $user = User::all();

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user=User::find($id);
        return view('admin.user.edit',compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'name'=>'required',
            'email'=>'required|string|email',
            'department_id'=>'required',
            'role_id'=>'required',
            'image'=>'mimes:jpeg,jpg,png',
            'start_from'=>'required',
            'designation'=>'required'
        ]);
        $data = $request->all();
        $user = User::find($id);
        if($request->hasFile('image')){
            $image = $request->image->hashName();
            $request->image->move(public_path('profile'),$image);
        }else{
            $image = $user->image;
        }
        if($request->password){
            $password = $request->password;
            $new_password = bcrypt($password);
        }
        else{
            $new_password = $user->password;
        }

        $data['image']=$image;
        
        $data['password']=$new_password;

        $user->update($data);
        return redirect(route('users.index'))->with('message','Users Updated Successfully!');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);
        $user->delete();
        return redirect()->back()->with('message','User Deleted Successfully!');
    }
}

resources/views/admin/user/index.blade.php
@extends('admin.partails.master')

@section('content')



<div class="d-flex justify-content-between align-items-center flex-wrap grid-margin">
    <div>
      <h4 class="mb-3 mb-md-0">{{__('globle.Welcome_to')}} {{__('sidebar.User')}}</h4>
    </div>
    <div class="d-flex align-items-center flex-wrap text-nowrap">
      <div class="input-group date datepicker dashboard-date mr-2 mb-2 mb-md-0 d-md-none d-xl-flex" id="dashboardDate">
        <span class="input-group-addon bg-transparent"><i data-feather="calendar" class=" text-primary"></i></span>
        <input type="text" class="form-control">
      </div>
      <button type="button" class="btn btn-outline-info btn-icon-text mr-2 d-none d-md-block">
        <i class="btn-icon-prepend" data-feather="download"></i>
        Import
      </button>
      <button type="button" class="btn btn-outline-primary btn-icon-text mr-2 mb-2 mb-md-0">
        <i class="btn-icon-prepend" data-feather="printer"></i>
        Print
      </button>
      {{-- <button type="button" class="btn btn-primary btn-icon-text mb-2 mb-md-0">
        <i class="btn-icon-prepend" data-feather="download-cloud"></i>
        Download Report
      </button> --}}
    </div>
  </div>

  


  <div class="mb-6">
    <div class="row">
        <div class="col-sm-12 col-md-6 d-flex mb-3">
            
            <div class="align-self-center">
                @if (@isset(auth()->user()->role->permission['name']['user']['can-add'])) 
                <a href="{{route('users.create')}}">

                    <button type="button" class="btn btn-primary btn-icon-text mb-2 mb-md-0">
                        <i class="btn-icon-prepend" data-feather="plus-square"></i>
                         {{__('sidebar.User')}}
                      </button>
                   
                </a>
                @endif
            </div>
        </div>
       
            
       
       
    </div>
</div>


  @if (Session::has('message'))
<div class="alert alert-success">
    {{Session::get('message')}}
</div>
    
@endif




<div class="table-responsive">

<div class="row">
            <div class="col-md-12 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        
        
        <div class="table-responsive">
          <table id="dataTableExample" class="table">
            <thead>
              <tr>
                <th>{{__('globle.No')}}</th>
                            <th>{{__('globle.Photo')}}</th>
                            <th>{{__('globle.Name')}}</th>
                            <th>{{__('globle.Email')}}</th>
                            {{-- <th class="py-6">Address</th>
                            <th class="py-6">Phone</th> --}}
                            <th>{{__('sidebar.Roles')}}</th>
                            <th>{{__('sidebar.Department')}}</th>
                            <th>{{__('globle.Designation')}}</th>
                            <th>{{__('globle.Start-Date')}}</th>
                            <th>{{__('globle.Action.Action')}}</th>
                        </tr>
              </tr>
            </thead>
            <tbody>
                @if (count($users)>0)
                    @foreach ($users as $key=>$user)
              
              <tr>
                


                <td>{{$user->id}}</td>
                        <td><img src="{{asset ('Profile')}}/{{$user->image}}" alt="" class="rounded-circle" style="width: 50px; height: 50px; object-fit: cover;"></td>
                        <td class="align-middle">{{$user->name}}</td>
                        <td >{{$user->email}}</td>
                        {{-- <td >{{$user->address}}</td>
                        <td class="align-middle">{{$user->mobile_number}}</td> --}}
                        <td><span class="badge badge-primary">{{$user->role->name}}</span></td>
                        <td >{{$user->department->name}}</td>
                        <td >{{$user->designation}}</td>
                        <td >{{$user->start_from}}</td>




                <td>
    
    
                    @if (@isset(auth()->user()->role->permission['name']['user']['can-edit']))       
                                <a href="{{route('users.edit',[$user->id])}}">
                                    
                                    <i class="link-icon" data-feather="edit"></i>
                                </a>
    
                                     
                    @endif
    
    
                    @if(isset(auth()->user()->role->permission['name']['user']['can-delete'])) 
                                    <!-- Button trigger modal -->
                                    <button type="button"  class="btn btn-link" data-toggle="modal" data-target="#exampleModal{{$user->id}}">
                                        <i class="link-icon text-danger" data-feather="trash"></i>
                                    </button>
                                @endif
    
                                    <!-- Modal -->
                                    <div class="modal fade" id="exampleModal{{$user->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                            <form action="{{route('users.destroy',[$user->id])}}" method="POST"> @csrf
                                                {{method_field('DELETE')}}
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLabel">{{__('globle.Action.Delete')}} {{__('sidebar.User')}}</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                    </div>
                                                    <div class="modal-body">
                                                    Do you want to delete
                                                    </div>
                                                    <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                                    <button type="submit" class="btn btn-danger">{{__('globle.Action.Delete')}}</button>
                                                    </div>
                                                </div>
                                            </form>
                                            
                                        </div>
                                    </div>
    
    
                </td>
                
              </tr>
    
              @endforeach
              @else
    
                    <div>No Table to Display</div>
    
                @endif
    
            </tbody>
          </table>
        </div>
      </div>
    </div>
            </div>
            
        </div>

        




   
@endsection